### PR TITLE
Improve changelog format

### PR DESCRIPTION
**Pull request by bjoernricks**
Update the changelog file and its format.

### CODE REVIEW

**Comment by bjoernricks** [comment]
> Your version headings are links without reference. The example uses a github link of the diff between two versions. Consider just removing the `[` and `]`.

@davidak looking at https://github.com/olivierlacan/keep-a-changelog/blob/master/CHANGELOG.md it seems by intention. GitHub creates a link for the diff changes since the release before :+1:

**Comment by bjoernricks** [comment]
Hmm not sure if the autolinking works for us too. But I can't find a difference to https://github.com/olivierlacan/keep-a-changelog/blob/master/CHANGELOG.md

**Comment by wiegandm** [comment]
> Hmm not sure if the autolinking works for us too. But I can't find a difference to https://github.com/olivierlacan/keep-a-changelog/blob/master/CHANGELOG.md

It isn't autolinking, those are [link reference definitions](https://github.github.com/gfm/#link-reference-definition) -- take a look at the bottom of the file.

**Comment by bjoernricks** [comment]
thanks @wiegandm! I've rebased the commits and added links in 0d12128. Should be fine now.

**Pull request merged**
